### ISSUE TITLE
RChain-API, RSign, issues, repo organization, ...

### ISSUE THREAD

**Issue by dckc** [JoshOrndorff/RChain-Status#6]
@JoshOrndorff , I can't assign issues in this repository to me. Want to invite me as collaborator?

On the other hand... unlike commits, which are fully decentralized and completely portable across forks / users / organizations, issues are closely associated with their repo.

I don't file issue on my repos... I'm treating your RChain-API as upstream for reasons we've discussed. Is it time to move these to the https://github.com/rchain organization? Along with the python client stuff?

**Comment by dckc** [comment]
The name RChain-API is a bit of a land-grab, no? That might make sense if it hosted the .proto files along with clients in scala, js, and python, but it's just the node module.

**Comment by dckc** [comment]
@glenbraun , @kennyrowe what's a good business process for allocating repositories under  https://github.com/rchain ? Maybe endorsement from a collection of people with aggregate [trust metric weight](https://github.com/rchain/bounties/wiki/Trust-Ratings) of 10 or more?

I think it can be done thru an API, so once we figure out a smart contract, we can delegate to it.

**Comment by JoshOrndorff** [comment]
I love the idea of getting this logic in a smart contract, but don't think we should delay the current issue until such a contract is feasible.

More immediately, moving RChain-API to live at github.com/rchain/rchain-api along with implementations in other languages like python and go (which Claire from Resonate is working on) would be wonderful. Plus it would reduce bloat in rchain/rchain by moving the python stuff out of there. I think @kitblake might also know how the process for new repos works since he created rchain/marketing.

RSign should definitely not be mixed in with status, and maybe should be your repo, @dckc ?

**Comment by dckc** [comment]
> ... but don't think we should delay the current issue until such a contract is feasible.

right... it was just a while-I'm-thinking-about-it brainstorm...

> More immediately, moving RChain-API to live at github.com/rchain/rchain-api along with implementations in other languages like python and go (which Claire from Resonate is working on) would be wonderful.

As we discussed, I'm leaving that to you.

> RSign should definitely not be mixed in with status, and maybe should be your repo, @dckc ?

Agreed: https://github.com/dckc/RSign

**Comment by dckc** [comment]
python code:
https://github.com/proof-media/rchain-notebook

https://github.com/rchain/rchain/tree/dev/node-client

**Comment by JoshOrndorff** [comment]
This is handled pretty well.

https://github.com/rchain-community/rchain-api
https://github.com/rchain-community/RSign

I'm content the leave the example dApps here for now.
